### ISSUE TITLE
Top module not set for synthesis run

### ISSUE THREAD

**Issue by vpatne** [erickerrigan/protoip#11]
When I run the lab3 of TEMPO Summer School - at the level of Synthesis - I am getting error:

Top module not set for synthesis run
Ensure that a valid value is provided for 'top'. The current value for 'top' can be changed using the 'Top Module Name' field under 'Project Settings', or using the 'set_property top' Tcl command 

I am using matlab 2018b and vivado 2017.4

**Comment by imciner2** [comment]
Can you please clarify which protoip command is issuing the error (the Vivado synthesis stage is called in several of the functions), and possibly give a capture of the command window output for the entire error?

**Comment by vpatne** [comment]
ip_prototype_build('project_name','my_project0','board_name','zedboard');

![synthesis_error](https://user-images.githubusercontent.com/37876195/55781150-20fdb380-5ac7-11e9-9937-4db5ab41c79c.jpg)
